Use post_id instead when neither title and post_name are available
Hit this problem when migrating from my wordpress archive. I happened
to have an untitled draft post with both <title> and <wp:post_name>
empty.

Existing migrator will throw the following error:

node_modules/hexo-migrator-wordpress/index.js:50
          postLink = postTitle.toLowerCase().split(' ').join('-');
                               ^
TypeError: Object #<Object> has no method 'toLowerCase'

In this case, post_id is the only thing we can use to avoid conflict,
not pretty but it can only happen to drafts anyway.